/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

/**
 *
 * @author Lenovo
 */
public class Pantalla extends javax.swing.JFrame {

    /**
     * Creates new form Pantalla
     */
    public Pantalla() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        Logo = new javax.swing.JLabel();
        NombreEmp = new javax.swing.JLabel();
        Txt1 = new javax.swing.JLabel();
        Txt2 = new javax.swing.JLabel();
        ImgRollo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        Desc1 = new javax.swing.JLabel();
        Desc2 = new javax.swing.JLabel();
        Desc3 = new javax.swing.JLabel();
        Desc4 = new javax.swing.JLabel();
        Desc5 = new javax.swing.JLabel();
        Desc6 = new javax.swing.JLabel();
        PelisDis = new javax.swing.JComboBox<>();
        jSeparator2 = new javax.swing.JSeparator();
        Boton = new javax.swing.JButton();
        PeliPort = new javax.swing.JLabel();
        ImgActor = new javax.swing.JLabel();
        ImgDirect = new javax.swing.JLabel();
        DescActor1 = new javax.swing.JLabel();
        DescDirect1 = new javax.swing.JLabel();
        DDD = new javax.swing.JLabel();
        DescActor2 = new javax.swing.JLabel();
        DescActor3 = new javax.swing.JLabel();
        DescActor4 = new javax.swing.JLabel();
        DescDirect2 = new javax.swing.JLabel();
        DescDirect3 = new javax.swing.JLabel();
        DescDirect4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(500, 500));
        setPreferredSize(new java.awt.Dimension(500, 500));

        jPanel2.setBackground(new java.awt.Color(204, 0, 0));
        jPanel2.setInheritsPopupMenu(true);
        jPanel2.setMaximumSize(new java.awt.Dimension(600, 600));
        jPanel2.setMinimumSize(new java.awt.Dimension(600, 600));
        jPanel2.setPreferredSize(new java.awt.Dimension(500, 500));

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Logo2-1.5px.png"))); // NOI18N

        NombreEmp.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        NombreEmp.setForeground(new java.awt.Color(255, 255, 255));
        NombreEmp.setText("De la vida como Pelicula");
        NombreEmp.setAlignmentX(0.5F);

        Txt1.setFont(new java.awt.Font("Vensim Sans", 0, 18)); // NOI18N
        Txt1.setForeground(new java.awt.Color(255, 255, 255));
        Txt1.setText("Bienvenido a \"De la Vida como Pelicula\", donde puedes ver libremente");
        Txt1.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        Txt2.setFont(new java.awt.Font("Vensim Sans", 0, 18)); // NOI18N
        Txt2.setForeground(new java.awt.Color(255, 255, 255));
        Txt2.setText("todas las peliculas que quieras, todo a un click de distancia.");

        ImgRollo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/rollo-img-20cm.png"))); // NOI18N
        ImgRollo.setText("|");

        Desc1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Desc1.setForeground(new java.awt.Color(255, 255, 255));
        Desc1.setText("Cuando Tim Lake cumple 21 años, su padre le dice un secreto: los hombres de su ");

        Desc2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Desc2.setForeground(new java.awt.Color(255, 255, 255));
        Desc2.setText("familia pueden viajar por el tiempo. A pesar de que él no puede cambiar la historia,");

        Desc3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Desc3.setForeground(new java.awt.Color(255, 255, 255));
        Desc3.setText("Tim decide mejorar su vida buscando una novia. Él conoce a Mary, se enamora y ");

        Desc4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Desc4.setForeground(new java.awt.Color(255, 255, 255));
        Desc4.setText("finalmente se gana su corazón con los viajes en el tiempo y un poco de astucia. Sin ");

        Desc5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Desc5.setForeground(new java.awt.Color(255, 255, 255));
        Desc5.setText("embargo, mientras su inusual vida progresa, Tim descubre que su habilidad especial ");

        Desc6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Desc6.setForeground(new java.awt.Color(255, 255, 255));
        Desc6.setText("no puede protegerlos de los problemas diarios de la vida.");

        PelisDis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Una cuestión de tiempo", "Diario de una Pasión", "En busca del destino", "Jumanji", "La La Land: ciudad de sueños", "La sociedad de los poetas muertos", "Sream 1", "Una noche en el museo 1", " " }));
        PelisDis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PelisDisActionPerformed(evt);
            }
        });

        Boton.setBackground(new java.awt.Color(102, 102, 102));
        Boton.setForeground(new java.awt.Color(255, 255, 255));
        Boton.setText("Buscar");
        Boton.setToolTipText("");
        Boton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonActionPerformed(evt);
            }
        });

        PeliPort.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cartel1.png"))); // NOI18N

        ImgActor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/imgActor1-250.png"))); // NOI18N

        ImgDirect.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/imgDirector1-250.png"))); // NOI18N

        DescActor1.setFont(new java.awt.Font("Vensim Sans", 1, 18)); // NOI18N
        DescActor1.setForeground(new java.awt.Color(255, 255, 255));
        DescActor1.setText("Domhnall");

        DescDirect1.setFont(new java.awt.Font("Vensim Sans", 1, 18)); // NOI18N
        DescDirect1.setForeground(new java.awt.Color(255, 255, 255));
        DescDirect1.setText("Richard");

        DDD.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        DDD.setForeground(new java.awt.Color(255, 255, 255));
        DDD.setText("Destacada Del Dia");

        DescActor2.setFont(new java.awt.Font("Vensim Sans", 1, 18)); // NOI18N
        DescActor2.setForeground(new java.awt.Color(255, 255, 255));
        DescActor2.setText("Gleeson");

        DescActor3.setFont(new java.awt.Font("Vensim Sans", 1, 18)); // NOI18N
        DescActor3.setForeground(new java.awt.Color(255, 255, 255));
        DescActor3.setText("41 años");

        DescActor4.setFont(new java.awt.Font("Vensim Sans", 1, 18)); // NOI18N
        DescActor4.setForeground(new java.awt.Color(255, 255, 255));
        DescActor4.setText("2 premios");

        DescDirect2.setFont(new java.awt.Font("Vensim Sans", 1, 18)); // NOI18N
        DescDirect2.setForeground(new java.awt.Color(255, 255, 255));
        DescDirect2.setText("Whalley");

        DescDirect3.setFont(new java.awt.Font("Vensim Sans", 1, 18)); // NOI18N
        DescDirect3.setForeground(new java.awt.Color(255, 255, 255));
        DescDirect3.setText("68 años");

        DescDirect4.setFont(new java.awt.Font("Vensim Sans", 1, 18)); // NOI18N
        DescDirect4.setForeground(new java.awt.Color(255, 255, 255));
        DescDirect4.setText("1 premio");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Logo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(NombreEmp)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(ImgActor, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(DescActor1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(DescActor2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(DescActor3, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(DescActor4, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(ImgDirect)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(DescDirect1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(DescDirect2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(DescDirect3, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(DescDirect4, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(35, 35, 35))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Desc6)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(Txt1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(Txt2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 635, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(PelisDis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(Boton))
                                            .addComponent(Desc2)
                                            .addComponent(Desc3)
                                            .addComponent(DDD, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Desc1)
                                            .addComponent(Desc4)
                                            .addComponent(Desc5))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(PeliPort, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)))
                                .addComponent(ImgRollo)))
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(NombreEmp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ImgRollo)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(Txt1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Txt2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(PelisDis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Boton))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DDD, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Desc1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Desc2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Desc3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Desc4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Desc5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Desc6))
                            .addComponent(PeliPort, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(85, 85, 85)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(DescActor1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DescActor2)
                                .addGap(18, 18, 18)
                                .addComponent(DescActor3)
                                .addGap(18, 18, 18)
                                .addComponent(DescActor4))
                            .addComponent(ImgActor)
                            .addComponent(ImgDirect, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(DescDirect1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DescDirect2)
                                .addGap(18, 18, 18)
                                .addComponent(DescDirect3)
                                .addGap(18, 18, 18)
                                .addComponent(DescDirect4))))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1463, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 718, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PelisDisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PelisDisActionPerformed

    }//GEN-LAST:event_PelisDisActionPerformed

    private void BotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonActionPerformed

    }//GEN-LAST:event_BotonActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Boton;
    private javax.swing.JLabel DDD;
    private javax.swing.JLabel Desc1;
    private javax.swing.JLabel Desc2;
    private javax.swing.JLabel Desc3;
    private javax.swing.JLabel Desc4;
    private javax.swing.JLabel Desc5;
    private javax.swing.JLabel Desc6;
    private javax.swing.JLabel DescActor1;
    private javax.swing.JLabel DescActor2;
    private javax.swing.JLabel DescActor3;
    private javax.swing.JLabel DescActor4;
    private javax.swing.JLabel DescDirect1;
    private javax.swing.JLabel DescDirect2;
    private javax.swing.JLabel DescDirect3;
    private javax.swing.JLabel DescDirect4;
    private javax.swing.JLabel ImgActor;
    private javax.swing.JLabel ImgDirect;
    private javax.swing.JLabel ImgRollo;
    private javax.swing.JLabel Logo;
    private javax.swing.JLabel NombreEmp;
    private javax.swing.JLabel PeliPort;
    private javax.swing.JComboBox<String> PelisDis;
    private javax.swing.JLabel Txt1;
    private javax.swing.JLabel Txt2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables

    private String Desc1(String c) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
